export interface StateInfo {
  code: string;
  name: string;
  url: string;
}

export const states: ReadonlyArray<StateInfo> = [
  { code: 'AL', name: 'Alabama', url: 'https://eforms.alacourt.gov/' },
  { code: 'AK', name: 'Alaska', url: 'https://courts.alaska.gov/forms/index.htm#name' },
  { code: 'AZ', name: 'Arizona', url: 'https://www.azcourts.gov/selfservicecenter/Forms' },
  { code: 'AR', name: 'Arkansas', url: 'https://www.arcourts.gov/forms-and-publications' },
  { code: 'CA', name: 'California', url: 'https://www.courts.ca.gov/1051.htm' },
  { code: 'CO', name: 'Colorado', url: 'https://www.coloradojudicial.gov/self-help/name-change' },
  { code: 'CT', name: 'Connecticut', url: 'https://www.jud.ct.gov/webforms/' },
  { code: 'DE', name: 'Delaware', url: 'https://courts.delaware.gov/forms/list.aspx?ftype=civil' },
  { code: 'FL', name: 'Florida', url: 'https://www.flcourts.gov/Resources-Services/Court-Improvement/Family-Courts/Family-Law-Self-Help-Information/Family-Law-Forms' },
  { code: 'GA', name: 'Georgia', url: 'https://georgiacourts.gov/' },
  { code: 'HI', name: 'Hawaii', url: 'https://www.courts.state.hi.us/self-help/courts/forms_court' },
  { code: 'ID', name: 'Idaho', url: 'https://courtselfhelp.idaho.gov/Forms/name' },
  { code: 'IL', name: 'Illinois', url: 'https://www.illinoiscourts.gov/forms/approved-forms/' },
  { code: 'IN', name: 'Indiana', url: 'https://www.in.gov/courts/iocs/' },
  { code: 'IA', name: 'Iowa', url: 'https://www.iowacourts.gov/for-the-public/representing-yourself/' },
  { code: 'KS', name: 'Kansas', url: 'https://www.kscourts.org/Public/Self-Help-Center' },
  { code: 'KY', name: 'Kentucky', url: 'https://kycourts.gov/Resources/Forms/Pages/default.aspx' },
  { code: 'LA', name: 'Louisiana', url: 'https://www.lasc.org/' },
  { code: 'ME', name: 'Maine', url: 'https://www.courts.maine.gov/forms/index.html' },
  { code: 'MD', name: 'Maryland', url: 'https://www.peoples-law.org/name-change' },
  { code: 'MA', name: 'Massachusetts', url: 'https://www.mass.gov/topics/probate-and-family-court-forms' },
  { code: 'MI', name: 'Michigan', url: 'https://www.michigan.gov/courts/administration/scao/forms' },
  { code: 'MN', name: 'Minnesota', url: 'https://www.mncourts.gov/Help-Topics/Name-Change.aspx' },
  { code: 'MS', name: 'Mississippi', url: 'https://courts.ms.gov/' },
  { code: 'MO', name: 'Missouri', url: 'https://www.courts.mo.gov/page.jsp?id=525' },
  { code: 'MT', name: 'Montana', url: 'https://courts.mt.gov/Forms/SRLForms' },
  { code: 'NE', name: 'Nebraska', url: 'https://supremecourt.nebraska.gov/self-help' },
  { code: 'NV', name: 'Nevada', url: 'https://www.nvcourts.gov/Self_Help/' },
  { code: 'NH', name: 'New Hampshire', url: 'https://www.courts.nh.gov/our-courts/circuit-court/probate-division/forms' },
  { code: 'NJ', name: 'New Jersey', url: 'https://www.njcourts.gov/self-help/name-change' },
  { code: 'NM', name: 'New Mexico', url: 'https://www.nmcourts.gov/self-help/' },
  { code: 'NY', name: 'New York', url: 'https://www.nycourts.gov/courthelp/Namechange/index.shtml' },
  { code: 'NC', name: 'North Carolina', url: 'https://www.nccourts.gov/help-topics/family-and-children/name-changes' },
  { code: 'ND', name: 'North Dakota', url: 'https://www.ndcourts.gov/legal-self-help' },
  { code: 'OH', name: 'Ohio', url: 'https://www.supremecourt.ohio.gov/courts/services-to-courts/forms/' },
  { code: 'OK', name: 'Oklahoma', url: 'https://www.oscn.net/static/forms/' },
  { code: 'OR', name: 'Oregon', url: 'https://www.courts.oregon.gov/forms/Pages/name-change.aspx' },
  { code: 'PA', name: 'Pennsylvania', url: 'https://www.pacourts.us/forms/for-the-public' },
  { code: 'RI', name: 'Rhode Island', url: 'https://www.courts.ri.gov/Pages/default.aspx' },
  { code: 'SC', name: 'South Carolina', url: 'https://www.sccourts.org/selfHelp/' },
  { code: 'SD', name: 'South Dakota', url: 'https://ujs.sd.gov/Forms/forms.aspx' },
  { code: 'TN', name: 'Tennessee', url: 'https://www.tncourts.gov/help-center' },
  { code: 'TX', name: 'Texas', url: 'https://www.txcourts.gov/programs-services/legal-forms/' },
  { code: 'UT', name: 'Utah', url: 'https://www.utcourts.gov/howto/namechange/' },
  { code: 'VT', name: 'Vermont', url: 'https://www.vermontjudiciary.org/self-help' },
  { code: 'VA', name: 'Virginia', url: 'https://www.vacourts.gov/forms/circuit/home.html' },
  { code: 'WA', name: 'Washington', url: 'https://www.courts.wa.gov/forms/' },
  { code: 'WV', name: 'West Virginia', url: 'http://www.courtswv.gov/lower-courts/circuit-forms.html' },
  { code: 'WI', name: 'Wisconsin', url: 'https://www.wicourts.gov/forms1/circuit/index.htm' },
  { code: 'WY', name: 'Wyoming', url: 'https://www.courts.state.wy.us/court-forms/' },
  { code: 'DC', name: 'District of Columbia', url: 'https://www.dccourts.gov/services/civil-matters/civil-actions/name-change' },
];
